apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployer-rb
  namespace: factory
subjects:
  - kind: ServiceAccount
    name: deployer-sa
    namespace: factory
  - kind: ServiceAccount
    name: internal-kubectl
    namespace: factory
roleRef:
  kind: ClusterRole
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io